version: 2.1

# CI009: Unpinned orb versions
orbs:
  node: circleci/node@volatile  # CI009: Using @volatile
  aws: circleci/aws-cli@latest  # CI009: Using @latest (not a valid semver)
  slack: circleci/slack  # CI009: No version specified

jobs:
  build:
    docker:
      - image: cimg/node:latest  # CI006 pattern (cross-platform)
    steps:
      - checkout
      - run:
          name: Install dependencies
          # CI013: Curl piped to shell
          command: |
            curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
            npm install
      
      - run:
          name: Build
          command: npm run build
      
      # CI014: Artifacts without path restrictions
      - store_artifacts:
          destination: artifacts

  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: pip install pytest
      - run: pytest tests/

  deploy_production:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      
      # CI010: SSH enabled in production workflow
      - add_ssh_keys:
          fingerprints:
            - "12:34:56:78:90:ab:cd:ef"
      
      - run:
          name: Deploy
          command: |
            # CI012: Hardcoded credentials in environment
            export API_KEY="sk_live_EXAMPLE_FAKE_NOT_REAL_abcdefghijk"
            export DB_PASSWORD="production_password_123"
            # CI013: Wget piped to shell
            wget -qO- https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
            ./deploy.sh

  security_scan:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run:
          name: Security scan
          # CI013: Another curl|bash example
          command: curl https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy_production:
          requires:
            - test
          filters:
            branches:
              only: main
      - security_scan:
          requires:
            - build
