name: Vulnerable CI Workflow

# CI002: Missing permissions key - defaults to broad access
on:
  pull_request_target:  # CI004: Dangerous with checkout
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    # CI002: No permissions defined
    
    steps:
      # CI001: Unpinned action using tag instead of SHA
      - name: Checkout code
        uses: actions/checkout@v4
      
      # CI001: Another unpinned action
      - name: Setup Node
        uses: actions/setup-node@v3
      
      # CI005: Hardcoded secret
      - name: Deploy
        env:
          API_KEY: ghp_EXAMPLE1234567890abcdefFAKETOKEN
          DATABASE_PASSWORD: super_secret_password_123
        run: |
          npm run deploy
      
      # CI003: Script injection - using github.event directly
      - name: Comment on PR
        run: |
          echo "Processing PR from ${{ github.event.pull_request.user.login }}"
          curl -X POST -d "message=${{ github.event.pull_request.title }}" https://api.example.com
      
      # CI013: Curl piped to shell
      - name: Install tools
        run: |
          curl -fsSL https://get.docker.com | bash
          wget -O- https://some-script.com/install.sh | sh
      
      # CI014: Unrestricted artifact upload
      - name: Upload everything
        uses: actions/upload-artifact@v3
        with:
          name: build-output

  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write-all  # CI002: Excessive permissions
    
    steps:
      - uses: actions/checkout@v3  # CI001: Unpinned
      
      # CI012: Hardcoded credentials in env vars
      - name: Deploy to production
        env:
          AWS_SECRET_ACCESS_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
          SLACK_TOKEN: xoxb-EXAMPLE-FAKE-TOKEN-NOT-REAL
        run: |
          echo "Deploying..."
          aws s3 sync ./build s3://mybucket
