stages:
  - build
  - test
  - security
  - deploy

variables:
  # CI008: Unprotected variables that look like secrets
  API_TOKEN: "sk-1234567890abcdefghijklmnopqrstuvwxyz"
  DATABASE_PASSWORD: "my_secret_password_123"
  DOCKER_HOST: tcp://docker:2375

build:
  stage: build
  # CI006: Unpinned image using :latest tag
  image: node:latest
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

test:
  stage: test
  # CI006: Using mutable tag
  image: python:3.11
  script:
    - pip install pytest
    - pytest
  # CI014: Artifacts without path restrictions
  artifacts:
    untracked: true

security_scan:
  stage: security
  image: alpine:latest  # CI006: :latest tag
  # CI007: Security job allows failure
  allow_failure: true
  script:
    # CI013: Curl piped to shell
    - curl -fsSL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
    - trivy fs .

deploy:
  stage: deploy
  image: ubuntu:latest  # CI006: :latest tag
  only:
    - main
  script:
    # CI012: Hardcoded credentials
    - export AWS_ACCESS_KEY_ID="AKIAIOSFODNN7EXAMPLE"
    - export AWS_SECRET_ACCESS_KEY="wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
    # CI013: Wget piped to shell
    - wget -O- https://get.helm.sh/helm-v3.12.0-linux-amd64.tar.gz | tar xz
    - ./linux-amd64/helm upgrade --install myapp ./chart/
  environment:
    name: production
    url: https://example.com

code_quality:
  stage: test
  image: codeclimate/codeclimate:latest  # CI006: :latest tag
  script:
    - codeclimate analyze
  allow_failure: true  # CI007: Not a security job but shows the pattern
